name: deploy-py-lambda
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: kohrongying/py-lambda-action@v1.0.2
      with:
        lambda_layer_arn: 'arn:aws:lambda:ap-east-1:128292546103'
        lambda_function_name: 'test-tg-noti-api'
        lambda_layer_publish: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-east-1'
